#!/usr/bin/env bash
# SUB/WAVE setup — idempotent, no sudo.
#
# In the new (single-compose + wizard) world this script is intentionally
# tiny. Its only jobs are:
#
#   1. Scaffold a 3-var .env (ADMIN_USER, ADMIN_PASS, SITE_URL) if missing —
#      anything richer (Navidrome, LLM, TTS, DJ persona) is collected by the
#      web wizard at /setup after the stack is up.
#   2. Create state/ with the right permissions (the icecast container also
#      does this on boot, but creating it host-side first means `docker
#      compose up` doesn't have to wait on the healthcheck just to satisfy
#      bind mounts).
#   3. Generate web/.env.local for native `npm run dev` workflows.
#
# Icecast passwords are NOT generated here — the subwave-icecast image
# generates them on first boot and writes them to state/icecast-secrets.env
# (mode 0644). Liquidsoap sources that file via its entrypoint.
#
# Emergency.mp3 and bed.mp3 are no longer rendered here — they're committed
# to sounds/ and baked into the controller + liquidsoap images at build time.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_DIR="${STATE_DIR:-$REPO_DIR/state}"
ROOT_ENV="$REPO_DIR/.env"
WEB_ENV_LOCAL="$REPO_DIR/web/.env.local"

say()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }

# ---- 1. State dir -----------------------------------------------------------
say "Using STATE_DIR=$STATE_DIR"
mkdir -p "$STATE_DIR"
chmod 777 "$STATE_DIR"

# ---- 2. Root .env (3 required vars) ----------------------------------------
if [[ ! -f "$ROOT_ENV" ]]; then
  ADMIN_PASS="$(openssl rand -hex 16)"
  say "Generating $ROOT_ENV (random ADMIN_PASS — change it later if you like)"
  cat > "$ROOT_ENV" <<EOF
# SUB/WAVE — required configuration
# Generated by scripts/setup.sh. Everything else is collected by the web
# wizard at /setup once the stack is up.
ADMIN_USER=admin
ADMIN_PASS=$ADMIN_PASS
SITE_URL=
EOF
  chmod 600 "$ROOT_ENV"
else
  say "$ROOT_ENV exists — leaving it alone"
fi

# ---- 3. web/.env.local for native dev (`cd web && npm run dev`) ------------
# Production runs web inside the Docker image behind Caddy, where /api and
# /stream.mp3 are same-origin — no env file needed. Native dev runs Next.js
# on the host on 7700 and must be told where the controller (7701) and
# Icecast (7702) live, otherwise every /api/* request 404s on the dev server.
if [[ ! -f "$WEB_ENV_LOCAL" ]]; then
  say "Generating $WEB_ENV_LOCAL for native dev"
  cat > "$WEB_ENV_LOCAL" <<EOF
NEXT_PUBLIC_API_URL=http://localhost:7701
NEXT_PUBLIC_STREAM_URL=http://localhost:7702/stream.mp3
EOF
else
  say "$WEB_ENV_LOCAL exists — leaving it alone"
fi

# Migration helper — if the operator is upgrading from the docker/.env +
# controller/.env layout, the new root .env doesn't carry their Navidrome
# creds or API keys. The controller will source state/setup-config.json (the
# wizard's overlay) but for upgraders it's worth flagging that env_file now
# reads ./.env so they can move whatever they want into the new file.
if [[ -f "$REPO_DIR/controller/.env" ]] || [[ -f "$REPO_DIR/docker/.env" ]]; then
  cat >&2 <<MIGRATE
[!] Detected legacy controller/.env or docker/.env from the pre-single-compose layout.
    They are NOT used anymore — the new compose files load ./.env (root) only.
    If those files have Navidrome creds or LLM API keys you want to keep,
    copy them into ./.env now (or skip and re-enter them in the web wizard).
MIGRATE
fi

cat <<EOF

Setup scaffolded.
  STATE_DIR: $STATE_DIR
  .env:      $ROOT_ENV   (admin creds + SITE_URL)

Next:
  Dev:       docker compose up -d
  Prod:      docker compose -f docker-compose.prod.yml up -d
  BYO proxy: docker compose -f docker-compose.byo-proxy.yml up -d

Then visit http://localhost:7700/onboarding to finish configuration
(Navidrome, LLM, TTS, DJ persona, jingles). Or run `npm run setup` for the
terminal-based equivalent.
EOF
