// AUTO-GENERATED by cli/scripts/embed-assets.ts — do not edit by hand.
// Regenerate with: npm --prefix cli run embed-assets
//
// These string constants are the source-of-truth content that
// `subwave init` materialises into SUBWAVE_HOME. CI verifies they match
// the original files at the repo root.


// docker-compose.yml
export const COMPOSE_YML = `# SUB/WAVE — production orchestration.
# Only Caddy is exposed on the host. Cloudflare terminates TLS in front.
# Broadcast (icecast2 + liquidsoap), Controller, and Web are all internal-only
# and reachable via Caddy's reverse proxy under one origin (/api, /stream.mp3, /).
#
# Image-first: every service pulls its baked image from GHCR by default. The
# build: blocks let \`docker compose build\` rebuild locally from a checkout,
# but the standard install never needs to clone — operators just need this
# file and a 3-line .env to boot.
#
# State persists in <repo>/state by default (override with STATE_DIR). It is a
# bind mount, so \`docker compose down -v\` (named-volume wipe) won't touch it —
# but it lives inside the project dir, so keep it clear of \`git clean -dffx\`.

x-state: &state-mount \${STATE_DIR:-./state}:/var/sub-wave

services:
  # -------------------------------------------------------------------------
  # CADDY — public edge, the only service bound to a host port
  # -------------------------------------------------------------------------
  caddy:
    image: ghcr.io/perminder-klair/subwave-caddy:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.caddy
    container_name: sub-wave-caddy
    restart: unless-stopped
    depends_on:
      - web
      - controller
      - broadcast
    ports:
      - "\${CADDY_PORT:-7700}:80"
    volumes:
      - caddy-data:/data
      - caddy-config:/config

  # -------------------------------------------------------------------------
  # BROADCAST — icecast2 endpoint + liquidsoap mixer in one container
  # -------------------------------------------------------------------------
  # The supervisor entrypoint resolves ICECAST_*_PASSWORD on first boot
  # (writing them to state/icecast-secrets.env for visibility), then launches
  # icecast2 and liquidsoap together. If either process dies the container
  # exits and compose restarts the pair as a unit.
  broadcast:
    image: ghcr.io/perminder-klair/subwave-broadcast:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.broadcast
    container_name: sub-wave-broadcast
    restart: unless-stopped
    environment:
      # All three are optional — leave blank in .env and the image generates
      # random values on first boot, persisting them to state/icecast-secrets.env.
      # To rotate: delete that file and restart broadcast + controller (the
      # controller doesn't actually source the file, but a settings reload
      # picks up any URL change cleanly).
      - ICECAST_SOURCE_PASSWORD=\${ICECAST_SOURCE_PASSWORD:-}
      - ICECAST_ADMIN_PASSWORD=\${ICECAST_ADMIN_PASSWORD:-}
      - ICECAST_RELAY_PASSWORD=\${ICECAST_RELAY_PASSWORD:-}
      # Keeps the hourly archive paths (%Y-%m-%d/%H-00.mp3) on local wall time.
      - TZ=\${TZ:-Europe/London}
    extra_hosts:
      # Lets Liquidsoap fetch Subsonic stream URLs that point at host services
      # (e.g. NAVIDROME_URL=http://host.docker.internal:4533) without leaking
      # the lookup to public DNS.
      - "host.docker.internal:host-gateway"
    volumes:
      - *state-mount
      - \${STATE_DIR:-./state}/logs:/var/log/liquidsoap
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:7702/status-json.xsl > /dev/null"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 15s

  # -------------------------------------------------------------------------
  # CONTROLLER — AI DJ brain
  # -------------------------------------------------------------------------
  controller:
    image: ghcr.io/perminder-klair/subwave-controller:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.controller
    container_name: sub-wave-controller
    restart: unless-stopped
    depends_on:
      broadcast:
        condition: service_healthy
    environment:
      # Enables the production-only admin gate: refuses to boot unless
      # ADMIN_USER + ADMIN_PASS are set in .env.
      - NODE_ENV=production
      # Schedule slots are stored by day-of-week + hour; resolveActiveShow()
      # reads them with date.getHours(). Without TZ the container runs in UTC
      # and fires shows an hour early during BST.
      - TZ=\${TZ:-Europe/London}
      # In-container path of the *state-mount below.
      - STATE_DIR=/var/sub-wave
      # In-container path of the sounds COPY'd into the image at build time.
      - SOUNDS_DIR=/sounds
      # Optional sidecar for Chatterbox + PocketTTS. The tts-heavy service
      # below is gated by \`--profile tts-heavy\`; when off, the URL is
      # unreachable and audio/chatterbox.ts + audio/pocketTts.ts silently
      # fall back to Piper (same behaviour as the default image today).
      - TTS_HEAVY_URL=\${TTS_HEAVY_URL:-http://tts-heavy:8080}
    env_file:
      # All controller config (Navidrome creds, LLM keys, ADMIN_*, etc.) lives
      # in the root .env. Vars not set are simply absent — settings.json takes
      # over for everything the first-run wizard manages.
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - *state-mount

  # -------------------------------------------------------------------------
  # WEB — Next.js listener UI
  # -------------------------------------------------------------------------
  web:
    image: ghcr.io/perminder-klair/subwave-web:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        # Needed at BUILD time for statically-rendered routes (robots, sitemap,
        # /listen, /landing) — Next bakes their metadata at build.
        - SITE_URL=\${SITE_URL:-}
        # NEXT_PUBLIC_* is inlined into the client bundle at BUILD time.
        - NEXT_PUBLIC_GA_ID=\${NEXT_PUBLIC_GA_ID:-}
    container_name: sub-wave-web
    restart: unless-stopped
    depends_on:
      - controller
    environment:
      - NODE_ENV=production
      - SUBWAVE_HOMEPAGE=\${SUBWAVE_HOMEPAGE:-player}
      # Also needed at RUNTIME: the homepage (/) is force-dynamic, so its
      # share-card tags render per-request. Define SITE_URL once in .env and
      # both build-arg and runtime env pick it up.
      - SITE_URL=\${SITE_URL:-}
      # Server-side base URL for generateMetadata on the force-dynamic homepage
      # to read the live station name from the controller. Internal compose
      # network name — not exposed to the browser (which uses /api via Caddy).
      - CONTROLLER_INTERNAL_URL=http://controller:7701

  # -------------------------------------------------------------------------
  # TTS-HEAVY (optional) — sidecar for Chatterbox + PocketTTS
  # -------------------------------------------------------------------------
  # Heavy PyTorch engines pulled out of the controller image so operators on
  # the pre-built ghcr.io images can opt into them without a custom rebuild
  # (issue #103). NOT started by default. Enable with:
  #
  #   docker compose --profile tts-heavy up -d
  #
  # The controller is wired with TTS_HEAVY_URL pointing here unconditionally;
  # when the profile is off the URL is unreachable and chatterbox.ts /
  # pocketTts.ts report unavailable, so the dispatcher falls back to Piper —
  # same behaviour as the default image today.
  #
  # See docker/Dockerfile.tts-heavy + docker/tts-heavy/server.py.
  tts-heavy:
    image: ghcr.io/perminder-klair/subwave-tts-heavy:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.tts-heavy
      args:
        # Optional — bake the gated PocketTTS cloning weights into the image at
        # build time. Usually unnecessary: setting HF_TOKEN in \`environment\`
        # below enables cloning at runtime (lazy download) without it.
        HF_TOKEN: \${HF_TOKEN:-}
        # Optional — install the CLAP audio-embedding stack (torch +
        # transformers + onnxruntime, ~1.5GB) into the analyzer venv. Needed
        # for the "sounds-like" audio similarity + sonic journeys; pair with
        # ANALYZE_AUDIO_EMBEDDING=1 below. Default off keeps the image lean.
        WITH_CLAP: \${WITH_CLAP:-0}
    # amd64-only image (heavy PyTorch stack); pinned so it runs under emulation
    # on arm64 hosts. The other services are multi-arch and auto-select.
    platform: linux/amd64
    container_name: sub-wave-tts-heavy
    restart: unless-stopped
    profiles: ["tts-heavy"]
    environment:
      # 'cpu' or 'cuda'. The default image is CPU-only — cuda needs a GPU
      # host + nvidia runtime; the server gracefully falls back to cpu when
      # CUDA isn't actually available.
      - TTS_HEAVY_DEVICE=\${TTS_HEAVY_DEVICE:-cpu}
      # Default voice id used by PocketTTS when a persona doesn't override it.
      - POCKET_TTS_VOICE=\${POCKET_TTS_VOICE:-alba}
      # Optional — enables PocketTTS zero-shot voice CLONING (issue #238). The
      # cloning weights (kyutai/pocket-tts) are gated on Hugging Face; without a
      # token the engine loads the open weights and cloned .wav voices revert to
      # a built-in. Accept the model terms on huggingface.co/kyutai/pocket-tts,
      # then put HF_TOKEN=hf_... in your root .env. Built-in voices need no token.
      - HF_TOKEN=\${HF_TOKEN:-}
      # Optional — compute CLAP audio embeddings in the analyze pass (needs an
      # image built with WITH_CLAP=1 above; without it this is a clean no-op
      # and the worker emits bpm/key only). Set ANALYZE_AUDIO_EMBEDDING=1 in
      # your root .env to enable. CLAP_MODEL picks the transformers checkpoint;
      # CLAP_MODEL_PATH points at a pre-exported ONNX audio encoder instead.
      - ANALYZE_AUDIO_EMBEDDING=\${ANALYZE_AUDIO_EMBEDDING:-}
      - CLAP_MODEL=\${CLAP_MODEL:-}
      - CLAP_MODEL_PATH=\${CLAP_MODEL_PATH:-}
    volumes:
      # Same shared mount as the controller — the sidecar writes WAVs into
      # /var/sub-wave/voice/* and the controller hands the path to Liquidsoap.
      - *state-mount
      # Persist the per-engine Hugging Face caches across container recreates.
      # Weights download at boot (the workers load the model before reporting
      # ready) — without these volumes that multi-GB fetch repeats on every
      # \`up -d --build\` / image pull / update. With them it happens once.
      - tts-heavy-chatterbox-cache:/opt/chatterbox/hf-cache
      - tts-heavy-pocket-cache:/opt/pocket-tts/hf-cache
      # CLAP weights for the analyzer (only populated when audio embeddings
      # are enabled and no local CLAP_MODEL_PATH is given).
      - tts-heavy-analyzer-cache:/opt/analyzer/hf-cache

volumes:
  caddy-data:
  caddy-config:
  tts-heavy-chatterbox-cache:
  tts-heavy-pocket-cache:
  tts-heavy-analyzer-cache:
`;

// docker-compose.byo.yml
export const COMPOSE_BYO_YML = `# SUB/WAVE — production orchestration without a bundled reverse proxy.
# Use this variant if you already run Traefik, nginx, an existing Caddy, or any
# other reverse proxy in front of your homelab. The three user-facing services
# bind directly to host ports and your proxy fronts them.
#
# Default host ports (override via root .env or your shell):
#   \${WEB_PORT:-7700}        → Next.js listener UI
#   \${CONTROLLER_PORT:-7701} → controller HTTP API
#   \${ICECAST_PORT:-7702}    → Icecast MP3 broadcast endpoint
#
# Liquidsoap stays internal-only — it lives inside the broadcast container
# alongside icecast and has no public surface.
#
# The web UI assumes same-origin routing for /api and /stream.mp3 by default
# (it's baked into the image at build time). To keep that working, point your
# proxy at a single hostname and replicate the route table from docker/Caddyfile:
#   /stream.mp3  → host:\${ICECAST_PORT}      (disable buffering for live audio)
#   /api/*       → host:\${CONTROLLER_PORT}   (strip the /api prefix)
#   everything   → host:\${WEB_PORT}
#
# If you need separate hostnames per surface, you'll have to rebuild the web
# image with NEXT_PUBLIC_API_URL / NEXT_PUBLIC_STREAM_URL set — those are
# baked at build time, not runtime.
#
# State persists in <repo>/state by default (override with STATE_DIR). It is a
# bind mount, so \`docker compose down -v\` won't touch it.

x-state: &state-mount \${STATE_DIR:-./state}:/var/sub-wave

services:
  # -------------------------------------------------------------------------
  # BROADCAST — icecast2 + liquidsoap in one container
  # -------------------------------------------------------------------------
  # The icecast HTTP port is bound to the host so the operator's reverse
  # proxy can front /stream.mp3. Liquidsoap is internal to this container.
  broadcast:
    image: ghcr.io/perminder-klair/subwave-broadcast:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.broadcast
    container_name: sub-wave-broadcast
    restart: unless-stopped
    environment:
      - ICECAST_SOURCE_PASSWORD=\${ICECAST_SOURCE_PASSWORD:-}
      - ICECAST_ADMIN_PASSWORD=\${ICECAST_ADMIN_PASSWORD:-}
      - ICECAST_RELAY_PASSWORD=\${ICECAST_RELAY_PASSWORD:-}
      - TZ=\${TZ:-Europe/London}
    ports:
      - "\${ICECAST_PORT:-7702}:7702"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - *state-mount
      - \${STATE_DIR:-./state}/logs:/var/log/liquidsoap
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:7702/status-json.xsl > /dev/null"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 15s

  # -------------------------------------------------------------------------
  # CONTROLLER — AI DJ brain, bound to host for your reverse proxy
  # -------------------------------------------------------------------------
  controller:
    image: ghcr.io/perminder-klair/subwave-controller:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.controller
    container_name: sub-wave-controller
    restart: unless-stopped
    depends_on:
      broadcast:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - TZ=\${TZ:-Europe/London}
      - STATE_DIR=/var/sub-wave
      - SOUNDS_DIR=/sounds
      # Optional sidecar for Chatterbox + PocketTTS. Gated by --profile tts-heavy
      # below; unreachable URL → fall back to Piper (no harm done).
      - TTS_HEAVY_URL=\${TTS_HEAVY_URL:-http://tts-heavy:8080}
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "\${CONTROLLER_PORT:-7701}:7701"
    volumes:
      - *state-mount

  # -------------------------------------------------------------------------
  # WEB — Next.js listener UI, bound to host for your reverse proxy
  # -------------------------------------------------------------------------
  web:
    image: ghcr.io/perminder-klair/subwave-web:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        - SITE_URL=\${SITE_URL:-}
        - NEXT_PUBLIC_GA_ID=\${NEXT_PUBLIC_GA_ID:-}
    container_name: sub-wave-web
    restart: unless-stopped
    depends_on:
      - controller
    environment:
      - NODE_ENV=production
      - SUBWAVE_HOMEPAGE=\${SUBWAVE_HOMEPAGE:-player}
      - SITE_URL=\${SITE_URL:-}
      # Server-side base URL for generateMetadata on the force-dynamic homepage
      # to read the live station name from the controller. Internal compose
      # network name — not exposed to the browser (which uses /api via Caddy).
      - CONTROLLER_INTERNAL_URL=http://controller:7701
    ports:
      - "\${WEB_PORT:-7700}:7700"
    # Same-origin (/api, /stream.mp3) is the default baked into the image.
    # Your external proxy is responsible for routing those paths to controller
    # and broadcast — see the header comment for the route table.

  # -------------------------------------------------------------------------
  # TTS-HEAVY (optional) — sidecar for Chatterbox + PocketTTS
  # -------------------------------------------------------------------------
  # See docker-compose.yml for the full rationale (issue #103). NOT started
  # by default. Enable with \`docker compose -f docker-compose.byo.yml \\
  #   --profile tts-heavy up -d\`. The controller falls back to Piper when
  # the URL is unreachable.
  tts-heavy:
    image: ghcr.io/perminder-klair/subwave-tts-heavy:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.tts-heavy
      args:
        # Optional — bake the gated PocketTTS cloning weights in at build time.
        # Runtime HF_TOKEN (below) enables cloning without it.
        HF_TOKEN: \${HF_TOKEN:-}
        # Optional — CLAP audio-embedding stack for the analyzer (~1.5GB);
        # pair with ANALYZE_AUDIO_EMBEDDING=1 below.
        WITH_CLAP: \${WITH_CLAP:-0}
    # amd64-only image (heavy PyTorch stack); pinned so it runs under emulation
    # on arm64 hosts. The other services are multi-arch and auto-select.
    platform: linux/amd64
    container_name: sub-wave-tts-heavy
    restart: unless-stopped
    profiles: ["tts-heavy"]
    environment:
      - TTS_HEAVY_DEVICE=\${TTS_HEAVY_DEVICE:-cpu}
      - POCKET_TTS_VOICE=\${POCKET_TTS_VOICE:-alba}
      # Optional — enables PocketTTS voice CLONING (issue #238). Cloning weights
      # are gated on Hugging Face; accept the terms at
      # huggingface.co/kyutai/pocket-tts and set HF_TOKEN in your root .env.
      # Built-in voices need no token.
      - HF_TOKEN=\${HF_TOKEN:-}
      # Optional — CLAP audio embeddings in the analyze pass (needs an image
      # built with WITH_CLAP=1 above; clean no-op otherwise). Set
      # ANALYZE_AUDIO_EMBEDDING=1 in your root .env to enable.
      - ANALYZE_AUDIO_EMBEDDING=\${ANALYZE_AUDIO_EMBEDDING:-}
      - CLAP_MODEL=\${CLAP_MODEL:-}
      - CLAP_MODEL_PATH=\${CLAP_MODEL_PATH:-}
    volumes:
      - *state-mount
      # Persist the per-engine Hugging Face caches across container recreates.
      # Weights download at boot (the workers load the model before reporting
      # ready) — without these volumes that multi-GB fetch repeats on every
      # \`up -d --build\` / image pull / update. With them it happens once.
      - tts-heavy-chatterbox-cache:/opt/chatterbox/hf-cache
      - tts-heavy-pocket-cache:/opt/pocket-tts/hf-cache
      # CLAP weights for the analyzer (only populated when audio embeddings
      # are enabled and no local CLAP_MODEL_PATH is given).
      - tts-heavy-analyzer-cache:/opt/analyzer/hf-cache

volumes:
  tts-heavy-chatterbox-cache:
  tts-heavy-pocket-cache:
  tts-heavy-analyzer-cache:
`;

// docker-compose.dev.yml
export const COMPOSE_DEV_YML = `# SUB/WAVE — dev compose (local smoke test).
# Runs: Broadcast (icecast2 + liquidsoap) + Controller. The Next.js listener
# UI runs separately via \`cd web && npm run dev\` so JSX changes hot-reload.
#
# State + sounds + radio.liq are bind-mounted from the repo so dev cycles
# don't need image rebuilds. The prod composes bake them into images instead.

x-state: &state-mount ./state:/var/sub-wave

services:
  # -------------------------------------------------------------------------
  # BROADCAST — icecast2 + liquidsoap in one container
  # -------------------------------------------------------------------------
  # Icecast HTTP exposed on :7702 for direct dev access (curl the stream,
  # hit /status-json.xsl, etc.). Liquidsoap is internal to this container.
  broadcast:
    image: ghcr.io/perminder-klair/subwave-broadcast:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.broadcast
    # No \`platform:\` pin in dev. On Apple Silicon, forcing linux/amd64 routes
    # liquidsoap through Rosetta/QEMU emulation where its clock_nanosleep
    # syscall fails with \`Unix.Unix_error(EUNKNOWNERR 0, "", "")\` — the
    # clock loop dies on every boot and Icecast ends up with no source.
    # The savonet/liquidsoap:v2.2.5 base is multi-arch, so building natively
    # (arm64 on M-series Macs, amd64 on Linux dev hosts) just works. Prod
    # composes still pin amd64 because the GHCR-published images are amd64
    # only for now.
    container_name: sub-wave-broadcast
    restart: unless-stopped
    ports:
      - "7702:7702"
    environment:
      # All three are optional — leave blank in .env and the image generates
      # random values on first boot, writing them to state/icecast-secrets.env.
      - ICECAST_SOURCE_PASSWORD=\${ICECAST_SOURCE_PASSWORD:-}
      - ICECAST_ADMIN_PASSWORD=\${ICECAST_ADMIN_PASSWORD:-}
      - ICECAST_RELAY_PASSWORD=\${ICECAST_RELAY_PASSWORD:-}
      - TZ=\${TZ:-Europe/London}
    extra_hosts:
      # Lets Liquidsoap fetch Subsonic stream URLs that point at host services
      # (e.g. NAVIDROME_URL=http://host.docker.internal:4533) without leaking
      # the lookup to public DNS.
      - "host.docker.internal:host-gateway"
    volumes:
      # Bind-mounts override the baked-in copies so dev edits to radio.liq and
      # new sounds appear on the next restart without an image rebuild.
      - ./liquidsoap/radio.liq:/etc/liquidsoap/radio.liq:ro
      - ./sounds:/sounds:ro
      - *state-mount
      - ./state/logs:/var/log/liquidsoap
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:7702/status-json.xsl > /dev/null"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 15s

  # -------------------------------------------------------------------------
  # CONTROLLER — the AI DJ brain
  # -------------------------------------------------------------------------
  controller:
    image: ghcr.io/perminder-klair/subwave-controller:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.controller
    platform: linux/amd64
    container_name: sub-wave-controller
    restart: unless-stopped
    depends_on:
      broadcast:
        condition: service_healthy
    environment:
      - TZ=\${TZ:-Europe/London}
      - STATE_DIR=/var/sub-wave
      - SOUNDS_DIR=/sounds
      # Optional sidecar for Chatterbox + PocketTTS. Gated by --profile tts-heavy
      # below; unreachable URL → fall back to Piper. Dev usage:
      #   docker compose -f docker-compose.dev.yml --profile tts-heavy up -d
      - TTS_HEAVY_URL=\${TTS_HEAVY_URL:-http://tts-heavy:8080}
    ports:
      - "7701:7701"
    env_file:
      # All controller config (Navidrome creds, LLM keys, ADMIN_*, etc.) lives
      # in the root .env. Vars not set are simply absent — settings.json takes
      # over for everything the wizard manages.
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Dev mode runs the controller under \`tsx watch\` against bind-mounted
    # source, so edits to controller/src/** restart the process inside the
    # container without a \`docker compose build\`. node_modules stays baked
    # into the image — we override src/ and scripts/ only. Prod composes
    # use the image's default CMD (\`tsx src/server.ts\`, no watch).
    command: ["node_modules/.bin/tsx", "watch", "src/server.ts"]
    volumes:
      # State + sounds are bind-mounted in dev so changes don't need rebuilds.
      - *state-mount
      - ./sounds:/sounds:ro
      # Source bind-mounts for hot reload. \`tsx watch\` picks up changes via
      # inotify. Don't mount the whole controller/ dir — that would shadow
      # /app/node_modules with the (possibly empty) host node_modules.
      - ./controller/src:/app/src
      - ./controller/scripts:/app/scripts

  # -------------------------------------------------------------------------
  # TTS-HEAVY (optional) — sidecar for Chatterbox + PocketTTS
  # -------------------------------------------------------------------------
  # NOT started by default. Enable with:
  #   docker compose -f docker-compose.dev.yml --profile tts-heavy up -d
  # See docker/Dockerfile.tts-heavy + docker/tts-heavy/server.py. First build
  # downloads ~3-4GB of model weights from Hugging Face — be patient.
  tts-heavy:
    image: ghcr.io/perminder-klair/subwave-tts-heavy:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.tts-heavy
      args:
        # Optional — bake the gated PocketTTS cloning weights in at build time.
        HF_TOKEN: \${HF_TOKEN:-}
        # Optional — CLAP audio-embedding stack for the analyzer (~1.5GB);
        # pair with ANALYZE_AUDIO_EMBEDDING=1 below.
        WITH_CLAP: \${WITH_CLAP:-0}
    platform: linux/amd64
    container_name: sub-wave-tts-heavy
    restart: unless-stopped
    profiles: ["tts-heavy"]
    environment:
      - TTS_HEAVY_DEVICE=\${TTS_HEAVY_DEVICE:-cpu}
      - POCKET_TTS_VOICE=\${POCKET_TTS_VOICE:-alba}
      # Optional — enables PocketTTS voice CLONING (issue #238). Cloning weights
      # are gated; accept terms at huggingface.co/kyutai/pocket-tts and set
      # HF_TOKEN in your .env. Built-in voices need no token.
      - HF_TOKEN=\${HF_TOKEN:-}
      # Optional — CLAP audio embeddings in the analyze pass (needs an image
      # built with WITH_CLAP=1 above; clean no-op otherwise).
      - ANALYZE_AUDIO_EMBEDDING=\${ANALYZE_AUDIO_EMBEDDING:-}
      - CLAP_MODEL=\${CLAP_MODEL:-}
      - CLAP_MODEL_PATH=\${CLAP_MODEL_PATH:-}
    volumes:
      - *state-mount
      # Persist the per-engine Hugging Face caches across container recreates.
      # Weights download at boot (the workers load the model before reporting
      # ready) — without these volumes that multi-GB fetch repeats on every
      # recreate. With them it happens once.
      - tts-heavy-chatterbox-cache:/opt/chatterbox/hf-cache
      - tts-heavy-pocket-cache:/opt/pocket-tts/hf-cache
      # CLAP weights for the analyzer (only populated when audio embeddings
      # are enabled and no local CLAP_MODEL_PATH is given).
      - tts-heavy-analyzer-cache:/opt/analyzer/hf-cache

volumes:
  tts-heavy-chatterbox-cache:
  tts-heavy-pocket-cache:
  tts-heavy-analyzer-cache:
`;

// .env.example
export const ENV_EXAMPLE = `# ═══════════════════════════════════════════════════════════════
#  SUB/WAVE — required configuration
# ═══════════════════════════════════════════════════════════════
#
# Just three vars are required to boot the stack. Everything else
# (Navidrome, LLM, TTS engine, DJ persona, …) is collected by the
# first-run wizard at http://<your-host>/onboarding after the stack is up.
#
# The wizard writes those to state/settings.json, which is the
# runtime source of truth. The optional overrides below are kept
# for 12-factor / CI / GitOps style deploys where env beats UI.

# Admin credentials gate the wizard + admin UI. Mandatory in prod
# (the controller refuses to boot without them when NODE_ENV=production).
ADMIN_USER=admin
ADMIN_PASS=                       # generate one: openssl rand -hex 16

# Public origin (used for absolute URLs, OG tags, manifest, sitemap).
# Example: https://radio.example.com
SITE_URL=

# ═══════════════════════════════════════════════════════════════
#  OPTIONAL — sensible defaults, uncomment to override
# ═══════════════════════════════════════════════════════════════

# Storage + locale
# STATE_DIR=./state
# TZ=Europe/London

# Web
# SUBWAVE_HOMEPAGE=player          # or 'landing' for the marketing host
# NEXT_PUBLIC_GA_ID=

# Image version (prod only — pin a release tag)
# SUBWAVE_VERSION=latest

# ───────── Ports (byo-proxy compose only) ─────────
# CADDY_PORT=7700
# WEB_PORT=7700
# CONTROLLER_PORT=7701
# ICECAST_PORT=7702

# ───────── Icecast secrets ─────────
# Leave blank — the broadcast image auto-generates these on first boot and
# writes them to state/icecast-secrets.env. Override here only if you need
# specific passwords (e.g. broadcasting to an external relay).
# To rotate: delete state/icecast-secrets.env and restart broadcast +
# controller. (The merged container holds both icecast and liquidsoap, so
# the old three-way restart is collapsed into one bounce.)
# ICECAST_SOURCE_PASSWORD=
# ICECAST_ADMIN_PASSWORD=
# ICECAST_RELAY_PASSWORD=

# ───────── Overrides for the wizard's fields ─────────
# These all live in state/settings.json after the wizard runs. Set them here
# only if you want env to win (12-factor / CI / GitOps style deploys).
# NAVIDROME_URL=http://host.docker.internal:4533
# NAVIDROME_USER=
# NAVIDROME_PASS=
# MUSIC_LIBRARY_PATH=
# TTS_SPEED=0.85
# AUTO_QUEUE_REFRESH_MINUTES=60
# Convenience only — seeds the News skill's feed on first boot. After that the
# file wins: edit it in /admin/skills or state/skills/news/SKILL.md (changing
# these vars won't move an already-scaffolded feed).
# NEWS_FEED_URL=http://feeds.bbci.co.uk/news/rss.xml
# NEWS_MAX_ITEMS=10

# ───────── Cloud LLM / TTS API keys ─────────
# The wizard accepts these in a form and writes them to state/secrets.env
# (which the controller sources on boot). Set here only for IaC-style provisioning.
# ANTHROPIC_API_KEY=
# OPENAI_API_KEY=
# GOOGLE_GENERATIVE_AI_API_KEY=
# OPENROUTER_API_KEY=
# DEEPSEEK_API_KEY=
# AI_GATEWAY_API_KEY=
# ELEVENLABS_API_KEY=
# SEARCH_API_KEY=tvly-...
`;

// cli/package.json#version (embedded so the compiled binary can self-identify
// — used by `subwave --version` and by the TUI release fetch URL).
export const CLI_VERSION = `0.13.0`;
