// AUTO-GENERATED by cli/scripts/embed-assets.ts — do not edit by hand.
// Regenerate with: npm --prefix cli run embed-assets
//
// These string constants are the source-of-truth content that
// `subwave init` materialises into SUBWAVE_HOME. CI verifies they match
// the original files at the repo root.


// docker-compose.yml
export const COMPOSE_YML = `# SUB/WAVE — production orchestration.
# Only Caddy is exposed on the host. Cloudflare terminates TLS in front.
# Icecast, Liquidsoap, Controller, and Web are all internal-only and reachable
# via Caddy's reverse proxy under one origin (/api, /stream.mp3, /).
#
# Image-first: every service pulls its baked image from GHCR by default. The
# build: blocks let \`docker compose build\` rebuild locally from a checkout,
# but the standard install never needs to clone — operators just need this
# file and a 3-line .env to boot.
#
# State persists in <repo>/state by default (override with STATE_DIR). It is a
# bind mount, so \`docker compose down -v\` (named-volume wipe) won't touch it —
# but it lives inside the project dir, so keep it clear of \`git clean -dffx\`.

x-state: &state-mount \${STATE_DIR:-./state}:/var/sub-wave

services:
  # -------------------------------------------------------------------------
  # CADDY — public edge, the only service bound to a host port
  # -------------------------------------------------------------------------
  caddy:
    image: ghcr.io/perminder-klair/subwave-caddy:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.caddy
    container_name: sub-wave-caddy
    restart: unless-stopped
    depends_on:
      - web
      - controller
      - icecast
    ports:
      - "\${CADDY_PORT:-7700}:80"
    volumes:
      - caddy-data:/data
      - caddy-config:/config

  # -------------------------------------------------------------------------
  # ICECAST — broadcast endpoint (internal only)
  # -------------------------------------------------------------------------
  icecast:
    image: ghcr.io/perminder-klair/subwave-icecast:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.icecast
    platform: linux/amd64
    container_name: sub-wave-icecast
    restart: unless-stopped
    environment:
      # All three are optional — leave blank in .env and the image generates
      # random values on first boot, persisting them to state/icecast-secrets.env.
      # To rotate: delete that file, restart icecast + liquidsoap + controller.
      - ICECAST_SOURCE_PASSWORD=\${ICECAST_SOURCE_PASSWORD:-}
      - ICECAST_ADMIN_PASSWORD=\${ICECAST_ADMIN_PASSWORD:-}
      - ICECAST_RELAY_PASSWORD=\${ICECAST_RELAY_PASSWORD:-}
    volumes:
      - *state-mount
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/sub-wave/icecast-secrets.env"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 3s

  # -------------------------------------------------------------------------
  # LIQUIDSOAP — mixer, pulls from queue file, broadcasts to Icecast
  # -------------------------------------------------------------------------
  liquidsoap:
    image: ghcr.io/perminder-klair/subwave-liquidsoap:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.liquidsoap
    container_name: sub-wave-liquidsoap
    restart: unless-stopped
    depends_on:
      icecast:
        condition: service_healthy
    environment:
      # Keeps the hourly archive paths (%Y-%m-%d/%H-00.mp3) on local wall time.
      - TZ=\${TZ:-Europe/London}
    extra_hosts:
      # Lets Liquidsoap fetch Subsonic stream URLs that point at host services
      # (e.g. NAVIDROME_URL=http://host.docker.internal:4533) without leaking
      # the lookup to public DNS.
      - "host.docker.internal:host-gateway"
    volumes:
      - *state-mount
      - \${STATE_DIR:-./state}/logs:/var/log/liquidsoap

  # -------------------------------------------------------------------------
  # CONTROLLER — AI DJ brain
  # -------------------------------------------------------------------------
  controller:
    image: ghcr.io/perminder-klair/subwave-controller:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.controller
    platform: linux/amd64
    container_name: sub-wave-controller
    restart: unless-stopped
    depends_on:
      liquidsoap:
        condition: service_started
      icecast:
        condition: service_healthy
    environment:
      # Enables the production-only admin gate: refuses to boot unless
      # ADMIN_USER + ADMIN_PASS are set in .env.
      - NODE_ENV=production
      # Schedule slots are stored by day-of-week + hour; resolveActiveShow()
      # reads them with date.getHours(). Without TZ the container runs in UTC
      # and fires shows an hour early during BST.
      - TZ=\${TZ:-Europe/London}
      # In-container path of the *state-mount below.
      - STATE_DIR=/var/sub-wave
      # In-container path of the sounds COPY'd into the image at build time.
      - SOUNDS_DIR=/sounds
    env_file:
      # All controller config (Navidrome creds, LLM keys, ADMIN_*, etc.) lives
      # in the root .env. Vars not set are simply absent — settings.json takes
      # over for everything the first-run wizard manages.
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - *state-mount

  # -------------------------------------------------------------------------
  # WEB — Next.js listener UI
  # -------------------------------------------------------------------------
  web:
    image: ghcr.io/perminder-klair/subwave-web:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        # Needed at BUILD time for statically-rendered routes (robots, sitemap,
        # /listen, /landing) — Next bakes their metadata at build.
        - SITE_URL=\${SITE_URL:-}
        # NEXT_PUBLIC_* is inlined into the client bundle at BUILD time.
        - NEXT_PUBLIC_GA_ID=\${NEXT_PUBLIC_GA_ID:-}
    container_name: sub-wave-web
    restart: unless-stopped
    depends_on:
      - controller
    environment:
      - NODE_ENV=production
      - SUBWAVE_HOMEPAGE=\${SUBWAVE_HOMEPAGE:-player}
      # Also needed at RUNTIME: the homepage (/) is force-dynamic, so its
      # share-card tags render per-request. Define SITE_URL once in .env and
      # both build-arg and runtime env pick it up.
      - SITE_URL=\${SITE_URL:-}

volumes:
  caddy-data:
  caddy-config:
`;

// docker-compose.byo.yml
export const COMPOSE_BYO_YML = `# SUB/WAVE — production orchestration without a bundled reverse proxy.
# Use this variant if you already run Traefik, nginx, an existing Caddy, or any
# other reverse proxy in front of your homelab. The three user-facing services
# bind directly to host ports and your proxy fronts them.
#
# Default host ports (override via root .env or your shell):
#   \${WEB_PORT:-7700}        → Next.js listener UI
#   \${CONTROLLER_PORT:-7701} → controller HTTP API
#   \${ICECAST_PORT:-7702}    → Icecast MP3 broadcast endpoint
#
# Liquidsoap stays internal-only — it has no public surface.
#
# The web UI assumes same-origin routing for /api and /stream.mp3 by default
# (it's baked into the image at build time). To keep that working, point your
# proxy at a single hostname and replicate the route table from docker/Caddyfile:
#   /stream.mp3  → host:\${ICECAST_PORT}      (disable buffering for live audio)
#   /api/*       → host:\${CONTROLLER_PORT}   (strip the /api prefix)
#   everything   → host:\${WEB_PORT}
#
# If you need separate hostnames per surface, you'll have to rebuild the web
# image with NEXT_PUBLIC_API_URL / NEXT_PUBLIC_STREAM_URL set — those are
# baked at build time, not runtime.
#
# State persists in <repo>/state by default (override with STATE_DIR). It is a
# bind mount, so \`docker compose down -v\` won't touch it.

x-state: &state-mount \${STATE_DIR:-./state}:/var/sub-wave

services:
  # -------------------------------------------------------------------------
  # ICECAST — broadcast endpoint, bound to host for your reverse proxy
  # -------------------------------------------------------------------------
  icecast:
    image: ghcr.io/perminder-klair/subwave-icecast:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.icecast
    platform: linux/amd64
    container_name: sub-wave-icecast
    restart: unless-stopped
    environment:
      - ICECAST_SOURCE_PASSWORD=\${ICECAST_SOURCE_PASSWORD:-}
      - ICECAST_ADMIN_PASSWORD=\${ICECAST_ADMIN_PASSWORD:-}
      - ICECAST_RELAY_PASSWORD=\${ICECAST_RELAY_PASSWORD:-}
    ports:
      - "\${ICECAST_PORT:-7702}:7702"
    volumes:
      - *state-mount
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/sub-wave/icecast-secrets.env"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 3s

  # -------------------------------------------------------------------------
  # LIQUIDSOAP — mixer, internal only (no public surface)
  # -------------------------------------------------------------------------
  liquidsoap:
    image: ghcr.io/perminder-klair/subwave-liquidsoap:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.liquidsoap
    container_name: sub-wave-liquidsoap
    restart: unless-stopped
    depends_on:
      icecast:
        condition: service_healthy
    environment:
      - TZ=\${TZ:-Europe/London}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - *state-mount
      - \${STATE_DIR:-./state}/logs:/var/log/liquidsoap

  # -------------------------------------------------------------------------
  # CONTROLLER — AI DJ brain, bound to host for your reverse proxy
  # -------------------------------------------------------------------------
  controller:
    image: ghcr.io/perminder-klair/subwave-controller:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.controller
    platform: linux/amd64
    container_name: sub-wave-controller
    restart: unless-stopped
    depends_on:
      liquidsoap:
        condition: service_started
      icecast:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - TZ=\${TZ:-Europe/London}
      - STATE_DIR=/var/sub-wave
      - SOUNDS_DIR=/sounds
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "\${CONTROLLER_PORT:-7701}:7701"
    volumes:
      - *state-mount

  # -------------------------------------------------------------------------
  # WEB — Next.js listener UI, bound to host for your reverse proxy
  # -------------------------------------------------------------------------
  web:
    image: ghcr.io/perminder-klair/subwave-web:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        - SITE_URL=\${SITE_URL:-}
        - NEXT_PUBLIC_GA_ID=\${NEXT_PUBLIC_GA_ID:-}
    container_name: sub-wave-web
    restart: unless-stopped
    depends_on:
      - controller
    environment:
      - NODE_ENV=production
      - SUBWAVE_HOMEPAGE=\${SUBWAVE_HOMEPAGE:-player}
      - SITE_URL=\${SITE_URL:-}
    ports:
      - "\${WEB_PORT:-7700}:7700"
    # Same-origin (/api, /stream.mp3) is the default baked into the image.
    # Your external proxy is responsible for routing those paths to controller
    # and icecast — see the header comment for the route table.
`;

// docker-compose.dev.yml
export const COMPOSE_DEV_YML = `# SUB/WAVE — dev compose (local smoke test).
# Runs: Icecast + Liquidsoap + Controller. The Next.js listener UI runs
# separately via \`cd web && npm run dev\` so JSX changes hot-reload.
#
# State + sounds + radio.liq are bind-mounted from the repo so dev cycles
# don't need image rebuilds. The prod composes bake them into images instead.

x-state: &state-mount ./state:/var/sub-wave

services:
  # -------------------------------------------------------------------------
  # ICECAST — broadcast endpoint, exposed for direct dev access
  # -------------------------------------------------------------------------
  icecast:
    image: ghcr.io/perminder-klair/subwave-icecast:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.icecast
    platform: linux/amd64
    container_name: sub-wave-icecast
    restart: unless-stopped
    ports:
      - "7702:7702"
    environment:
      # All three are optional — leave blank in .env and the image generates
      # random values on first boot, writing them to state/icecast-secrets.env
      # so liquidsoap reads the same values.
      - ICECAST_SOURCE_PASSWORD=\${ICECAST_SOURCE_PASSWORD:-}
      - ICECAST_ADMIN_PASSWORD=\${ICECAST_ADMIN_PASSWORD:-}
      - ICECAST_RELAY_PASSWORD=\${ICECAST_RELAY_PASSWORD:-}
    volumes:
      - *state-mount
    healthcheck:
      # The entrypoint writes the secrets file before exec'ing icecast, so the
      # file's existence is the cleanest "ready for liquidsoap" signal.
      test: ["CMD-SHELL", "test -f /var/sub-wave/icecast-secrets.env"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 3s

  # -------------------------------------------------------------------------
  # LIQUIDSOAP — pulls from queue file, broadcasts to Icecast
  # -------------------------------------------------------------------------
  liquidsoap:
    image: ghcr.io/perminder-klair/subwave-liquidsoap:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.liquidsoap
    container_name: sub-wave-liquidsoap
    restart: unless-stopped
    depends_on:
      icecast:
        condition: service_healthy
    environment:
      - TZ=\${TZ:-Europe/London}
    extra_hosts:
      # Lets Liquidsoap fetch Subsonic stream URLs that point at host services
      # (e.g. NAVIDROME_URL=http://host.docker.internal:4533) without leaking
      # the lookup to public DNS.
      - "host.docker.internal:host-gateway"
    volumes:
      # Bind-mounts override the baked-in copies so dev edits to radio.liq and
      # new sounds appear on the next restart without an image rebuild.
      - ./liquidsoap/radio.liq:/etc/liquidsoap/radio.liq:ro
      - ./sounds:/sounds:ro
      - *state-mount
      - ./state/logs:/var/log/liquidsoap

  # -------------------------------------------------------------------------
  # CONTROLLER — the AI DJ brain
  # -------------------------------------------------------------------------
  controller:
    image: ghcr.io/perminder-klair/subwave-controller:\${SUBWAVE_VERSION:-latest}
    build:
      context: .
      dockerfile: docker/Dockerfile.controller
    platform: linux/amd64
    container_name: sub-wave-controller
    restart: unless-stopped
    depends_on:
      liquidsoap:
        condition: service_started
      icecast:
        condition: service_healthy
    environment:
      - TZ=\${TZ:-Europe/London}
      - STATE_DIR=/var/sub-wave
      - SOUNDS_DIR=/sounds
    ports:
      - "7701:7701"
    env_file:
      # All controller config (Navidrome creds, LLM keys, ADMIN_*, etc.) lives
      # in the root .env. Vars not set are simply absent — settings.json takes
      # over for everything the wizard manages.
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Dev mode runs the controller under \`tsx watch\` against bind-mounted
    # source, so edits to controller/src/** restart the process inside the
    # container without a \`docker compose build\`. node_modules stays baked
    # into the image — we override src/ and scripts/ only. Prod composes
    # use the image's default CMD (\`tsx src/server.ts\`, no watch).
    command: ["node_modules/.bin/tsx", "watch", "src/server.ts"]
    volumes:
      # State + sounds are bind-mounted in dev so changes don't need rebuilds.
      - *state-mount
      - ./sounds:/sounds:ro
      # Source bind-mounts for hot reload. \`tsx watch\` picks up changes via
      # inotify. Don't mount the whole controller/ dir — that would shadow
      # /app/node_modules with the (possibly empty) host node_modules.
      - ./controller/src:/app/src
      - ./controller/scripts:/app/scripts
`;

// .env.example
export const ENV_EXAMPLE = `# ═══════════════════════════════════════════════════════════════
#  SUB/WAVE — required configuration
# ═══════════════════════════════════════════════════════════════
#
# Just three vars are required to boot the stack. Everything else
# (Navidrome, LLM, TTS engine, DJ persona, …) is collected by the
# first-run wizard at http://<your-host>/onboarding after the stack is up.
#
# The wizard writes those to state/settings.json, which is the
# runtime source of truth. The optional overrides below are kept
# for 12-factor / CI / GitOps style deploys where env beats UI.

# Admin credentials gate the wizard + admin UI. Mandatory in prod
# (the controller refuses to boot without them when NODE_ENV=production).
ADMIN_USER=admin
ADMIN_PASS=                       # generate one: openssl rand -hex 16

# Public origin (used for absolute URLs, OG tags, manifest, sitemap).
# Example: https://radio.example.com
SITE_URL=

# ═══════════════════════════════════════════════════════════════
#  OPTIONAL — sensible defaults, uncomment to override
# ═══════════════════════════════════════════════════════════════

# Storage + locale
# STATE_DIR=./state
# TZ=Europe/London

# Web
# SUBWAVE_HOMEPAGE=player          # or 'landing' for the marketing host
# NEXT_PUBLIC_GA_ID=

# Image version (prod only — pin a release tag)
# SUBWAVE_VERSION=latest

# ───────── Ports (byo-proxy compose only) ─────────
# CADDY_PORT=7700
# WEB_PORT=7700
# CONTROLLER_PORT=7701
# ICECAST_PORT=7702

# ───────── Icecast secrets ─────────
# Leave blank — the icecast image auto-generates these on first boot and
# writes them to state/icecast-secrets.env. Override here only if you need
# specific passwords (e.g. broadcasting to an external relay).
# To rotate: delete state/icecast-secrets.env and restart all three of
# icecast, liquidsoap, and controller (the latter two cache env at startup).
# ICECAST_SOURCE_PASSWORD=
# ICECAST_ADMIN_PASSWORD=
# ICECAST_RELAY_PASSWORD=

# ───────── Overrides for the wizard's fields ─────────
# These all live in state/settings.json after the wizard runs. Set them here
# only if you want env to win (12-factor / CI / GitOps style deploys).
# NAVIDROME_URL=http://host.docker.internal:4533
# NAVIDROME_USER=
# NAVIDROME_PASS=
# MUSIC_LIBRARY_PATH=
# TTS_SPEED=0.85
# AUTO_QUEUE_REFRESH_MINUTES=60
# NEWS_FEED_URL=http://feeds.bbci.co.uk/news/rss.xml
# NEWS_MAX_ITEMS=10

# ───────── Cloud LLM / TTS API keys ─────────
# The wizard accepts these in a form and writes them to state/secrets.env
# (which the controller sources on boot). Set here only for IaC-style provisioning.
# ANTHROPIC_API_KEY=
# OPENAI_API_KEY=
# GOOGLE_GENERATIVE_AI_API_KEY=
# OPENROUTER_API_KEY=
# DEEPSEEK_API_KEY=
# AI_GATEWAY_API_KEY=
# ELEVENLABS_API_KEY=
# SEARCH_API_KEY=tvly-...
`;
